# Use a imagem oficial do Node.js como base
FROM node:18-alpine

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o arquivo package.json e package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instale as dependências do aplicativo
RUN npm install

# Copie o restante do código do aplicativo para o diretório de trabalho
COPY . .

# Comando para iniciar o servidor em modo de desenvolvimento e bind em todas as interfaces
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5000"]

# Exponha a porta que o contêiner irá usar
EXPOSE 5000